---
  - name: Install Common Packages
    hosts: web
    become: yes

    tasks: 
      - name: Update apt cache
        apt: 
          update_cache: yes
          
      - name: Install required packages
        apt: 
          name:
            - git
            - curl
            - unzip
            - vim
            - htop
          state: present
